import Head from "next/head";
import { Col, Container, Form, Row } from "react-bootstrap";
import { useState } from "react";
import { useRouter } from "next/router";
import Image from "next/image";

// File Import
import { Header, Footer } from "@/component/common";
import { products, relatedProducts } from "@/constant";
import { ProductItem, ProductSlider } from "@/component/product";
import StarIcon from "@/assets/images/icons/star.png";

const stars = [1, 2, 3, 4, 5];

export default function ProductDetails() {
  const route = useRouter();

  const { id }: any = route.query;
  const product: any = products?.find((product) => product.id === parseInt(id));

  return (
    <>
      <Head>
        <title>Avatown App</title>
        <meta name="description" content="Generated by Avatown App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Area  */}
      <Header />

      {/* Main Area */}
      <section className="main-content">
        <Container>
          <Row>
            {/* Products Slider and show images*/}
            <Col md={5} className="py-4">
              <ProductSlider productImage={product?.image} />
            </Col>

            {/* Product information and description */}
            <Col md={7} className="py-4">
              <div className="product-item product-details">
                <div className="product-content">
                  <h4 className="title">{product?.title}</h4>

                  <div className="author-info d-flex align-items-center">
                    <div className="author-thumb">
                      <Image src={product?.author?.thumb} alt="Author Icon" />
                    </div>
                    <div className="author-name">{product?.author?.name}</div>
                  </div>

                  <div className="rating d-flex align-items-center">
                    <div className="icon">
                      {stars?.map((star, index) => (
                        <Image key={index} src={StarIcon} alt="Star" />
                      ))}
                    </div>
                    <div className="value">
                      {`(${product?.rating?.value} & ${product?.rating?.likes} reviews)`}
                    </div>
                  </div>
                  <div className="pricing d-flex align-items-center">
                    <h6 className="title mb-0 me-2">Price: </h6>
                    <span>${product?.price}</span>
                    <del>${product?.price + 30} </del>
                  </div>

                  <div className="product-info mb-4">
                    <h6 className="title">Product Info: </h6>
                    <ul className="px-4">
                      <li>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      </li>
                      <li>Sed blandit magna vel sapien euismod malesuada.</li>
                      <li>
                        Maecenas nec sapien feugiat, ornare metus in, eleifend
                        nunc.
                      </li>
                      <li>Phasellus sagittis erat at enim porta congue.</li>
                      <li>Sed blandit magna vel sapien euismod malesuada.</li>
                      <li>
                        Maecenas nec sapien feugiat, ornare metus in, eleifend
                        nunc.
                      </li>
                    </ul>
                  </div>

                  <div className="quantity-info d-flex align-items-center mb-2">
                    <h6 className="title me-2">Quantity: </h6>
                    <div className="cart-action">
                      <span>-</span>
                      <span className="">2</span>
                      <span>+</span>
                    </div>
                  </div>

                  <div className="quantity-info mb-3 d-flex align-items-center">
                    <h6 className="title mb-0 me-2">Available Product: </h6>
                    <span className="stock">In Stock</span>
                  </div>

                  <div className="action-btn mb-4 d-flex align-items-center justify-content-between">
                    <button className="custom-btn buy-now">Buy Now</button>
                    <button className="custom-btn add-cart">Add Cart</button>
                  </div>

                  <div className="product-info mb-4">
                    <h6 className="title">Report Abuse: </h6>
                    <ul className="px-3">
                      <li>Categories: Samsung, HTC, Microsoft</li>
                      <li>Tag: gadget, device, electric</li>
                    </ul>
                  </div>
                </div>
              </div>
            </Col>
          </Row>

          {/* Related Products */}
          <div className="related-products-wrapper py-5">
            <h3 className="section-title mb-3">Related Products</h3>
            <Row>
              {relatedProducts?.map((product, index) => (
                <ProductItem key={index} product={product} />
              ))}
            </Row>
          </div>
        </Container>
      </section>

      {/* Footer Area */}
      <Footer />
    </>
  );
}
